import { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { apiPatch } from "@/lib/api";
import type { Project } from "@/lib/skipti";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

const fields = [{ key: "completed", label: "Completed" }, { key: "in_progress", label: "In progress" }, { key: "blockers", label: "Blockers" }, { key: "decisions", label: "Decisions" }, { key: "next_steps", label: "Next steps" }] as const;
export function ProjectEditor({ project, close }: { project: Project; close: () => void }) {
  const client = useQueryClient(); const [name, setName] = useState(project.name); const [description, setDescription] = useState(project.description); const [stack, setStack] = useState(project.stack.join(", ")); const [status, setStatus] = useState(project.status);
  const [state, setState] = useState(Object.fromEntries(fields.map(({ key }) => [key, project[key].join("\n")])));
  const save = useMutation({ mutationFn: () => apiPatch<Project>(`/projects/${project.id}`, { expected_revision: project.revision, name: name.trim(), description: description.trim(), stack: stack.split(",").map((item) => item.trim()).filter(Boolean), status, ...Object.fromEntries(fields.map(({ key }) => [key, state[key].split("\n").map((item) => item.trim()).filter(Boolean)])) }), onSuccess: () => { for (const queryKey of [["project", project.id], ["project-history", project.id], ["projects"], ["overview"]]) client.invalidateQueries({ queryKey }); close(); toast.success("Project saved as a new revision"); }, onError: (error) => { client.invalidateQueries({ queryKey: ["project", project.id] }); toast.error(error.message); } });
  return <form className="panel mb-8 p-6" onSubmit={(e) => { e.preventDefault(); save.mutate(); }} data-testid="project-edit-form"><h2 className="font-heading text-3xl">Edit project</h2><p className="mt-2 text-xs text-muted-foreground">Each save creates a revision. Use one item per line for progress and decisions.</p><div className="mt-6 grid gap-5 md:grid-cols-2"><div><label className="mb-2 block text-xs" htmlFor="edit-project-name">Name</label><Input id="edit-project-name" value={name} onChange={(e) => setName(e.target.value)} required minLength={2} maxLength={120} /></div><div><label className="mb-2 block text-xs" htmlFor="edit-project-status">Status</label><select id="edit-project-status" className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm" value={status} onChange={(e) => setStatus(e.target.value as Project["status"])}>{["active", "paused", "archived"].map((s) => <option key={s}>{s}</option>)}</select></div><div className="md:col-span-2"><label className="mb-2 block text-xs" htmlFor="edit-project-description">Description</label><Textarea id="edit-project-description" value={description} onChange={(e) => setDescription(e.target.value)} required minLength={3} maxLength={2000} /></div><div className="md:col-span-2"><label className="mb-2 block text-xs" htmlFor="edit-project-stack">Technologies, separated by commas</label><Input id="edit-project-stack" value={stack} onChange={(e) => setStack(e.target.value)} /></div>{fields.map(({ key, label }) => <div key={key}><label className="mb-2 block text-xs" htmlFor={`edit-${key}`}>{label}</label><Textarea id={`edit-${key}`} value={state[key]} onChange={(e) => setState((current) => ({ ...current, [key]: e.target.value }))} /></div>)}</div><div className="mt-6 flex gap-3"><Button type="submit" disabled={save.isPending || name.trim().length < 2 || description.trim().length < 3}>Save revision {project.revision + 1}</Button><Button type="button" variant="outline" onClick={close}>Cancel</Button></div></form>;
}
