import { Link } from "react-router-dom";
import { buttonVariants } from "@/components/ui/button";
const questions = [
  ["How do I get started?", "Create an account, complete the six-question Persona interview, and approve the useful context. You can also add entries directly in Persona core. Create a Project Holder for each project."],
  ["What does the AI receive?", "Skipti retrieves approved context that matches your question. The playground shows each selected entry. Sensitive Persona entries are excluded from AI retrieval, temporary passes, and Markdown exports."],
  ["How do project revisions work?", "Describe progress, review the proposed changes, then approve them. You can also edit the project directly. Each accepted change creates a revision, and restoring an earlier revision creates a new checkpoint."],
  ["Can I import files?", "A folder can contain up to 500 files and 50 MB. Private storage keeps the originals in Supabase. Context-only import accepts UTF-8 text and code files, keeps up to 20,000 characters per file as project context, and discards the originals."],
  ["How does temporary sharing work?", "Choose the context permissions and expiration for a Persona Pass. A device link can be redeemed once for read-only guest chat. The AI link allows plain-text retrieval until expiry or revocation. Anyone with either link can use its allowed access, so share it carefully."],
  ["What happens when I revoke a pass?", "Further context retrieval and guest AI responses are blocked. Information someone already saw cannot be erased remotely. Guest chat is deleted when the session ends or is revoked, unless you choose to retain it until expiry."],
  ["Why is AI chat unavailable?", "The site owner needs to configure a Gemini API key or an Emergent integration key. Account sign-in and private storage also require a configured Supabase project. Setup status appears in the dashboard."],
  ["How can I connect an MCP client?", "Generate a token in Settings, copy your site's MCP endpoint from the dashboard, and configure a compatible client with Bearer authentication. Generating a new token revokes the previous one. Keep the token private."],
];
export default function Help() { return <main className="mx-auto max-w-4xl px-5 py-12"><nav className="flex items-center justify-between"><Link to="/" className="font-heading text-3xl">Skipti AI</Link><Link to="/dashboard" className={buttonVariants({ variant: "outline", size: "sm" })}>Open workspace</Link></nav><header className="my-12"><p className="text-xs uppercase tracking-widest text-[#c47a91]">Help & privacy</p><h1 className="mt-3 font-heading text-5xl">Make your context work for you.</h1><p className="mt-4 text-sm leading-6 text-muted-foreground">A practical guide to accounts, projects, files, and temporary access.</p></header><section className="panel divide-y divide-border">{questions.map(([question, answer]) => <details key={question} className="p-6"><summary className="cursor-pointer text-base font-medium">{question}</summary><p className="mt-4 text-sm leading-7 text-muted-foreground">{answer}</p></details>)}</section><p className="mt-8 text-xs leading-6 text-muted-foreground">Account identity is managed by Supabase. Approved context and project records are stored by Skipti. Selected context and your question are sent to the configured AI provider only when you use AI features. Use Settings to export context, Persona core to edit or delete entries, and project pages to remove imported files.</p><Link className="mt-8 inline-block text-sm text-[#d7a0b1]" to="/">Back home</Link></main>; }
